si17-1: As a user I want to sign-up
nestcollective/si2017-project pull request #2
Opened 2017-07-31 09:39 UTC by DCoelhoM

si17-2: As a user I want to be able to confirm my email address, si17-3: As a registered user I want to be able to login, si17-27: As an authenticated user I want to be able to logout

2017-07-31 19:09 UTC, pcioga requested changes

2017-07-31 19:09 UTC, pcioga commented on app/models/user.rb
> +
podem adicionar já validações como uniqness do email, etc.

2017-08-01 09:01 UTC, FranciscoMSM requested changes
This PullRequest cannot be accepted without ESLint configuration.

2017-08-01 09:01 UTC, FranciscoMSM commented on app/controllers/users/sessions_controller.rb
> +      render json: { error: 'Credentials not matching' }
Este erro deveria estar nos ficheiros das traduções

2017-08-01 09:01 UTC, FranciscoMSM commented on config/application.rb
> +    #config.i18n.default_locale = :'pt'
descomentar isto

2017-08-01 09:01 UTC, FranciscoMSM commented on config/routes.rb
> +end
Newline in the EOF

2017-08-01 09:01 UTC, FranciscoMSM commented on frontend/src/App.css
> +}
estilos desnecessários

2017-08-01 09:01 UTC, FranciscoMSM commented on frontend/src/App.js
> +export default App;
empty component?

2017-08-01 09:01 UTC, FranciscoMSM commented on frontend/src/components/SignupScreen.js
> +export default SignupScreen;
Vamos tentar aqui modular um bocadinho este método de render e fazer um component que tenha este Input, label e erro, também terá que receber uma prop 'type' e uma prop 'style'

2017-08-01 16:22 UTC, pcioga approved these changes

2017-08-02 09:14 UTC, FranciscoMSM requested changes
Faltam as validações do model do user, e temos que modular as async calls à API da parte do frontend

2017-08-02 13:42 UTC, FranciscoMSM approved these changes

2017-08-02 13:42 UTC, FranciscoMSM commented on frontend/src/components/HomeScreen.js
> +  }).isRequired,
Mete só as PropTypes das props que necessitas, pode causar confusão se estiverem a mais e não forem utilizadas, neste caso mete só o email

2017-08-02 13:43 UTC, FranciscoMSM approved these changes

2017-08-02 13:57 UTC, merged